/* Copyright (c) 2026 Simon Peter
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#import <Foundation/Foundation.h>

#import "GSHelpFormatDetector.h"
#import "GSHelpParser.h"

@class GSHelpDocument;

/* Parser for GNUstep's gsdoc XML documentation markup (the format
 * generated by autogsdoc and used across -base/-gui/-back manuals).
 *
 * The defining quirk of gsdoc sources is that their pretty-printed XML
 * indentation leaks INTO the prose: text content carries literal tabs
 * and runs of spaces from the source layout.  This parser therefore
 * normalizes every mixed-content text run (whitespace runs collapse to
 * one space) while keeping <example> blocks verbatim.
 *
 * Unknown elements are walked transparently, so documents using newer
 * gsdoc vocabulary still render their prose instead of failing. */
@interface GSGSdocParser : NSObject <GSHelpParser>

@end
