include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

BUNDLE_NAME = Battery
BUNDLE_EXTENSION = .gsmenuextra

Battery_PRINCIPAL_CLASS = BatteryExtra
Battery_OBJC_FILES = BatteryExtra.m

ADDITIONAL_OBJCFLAGS += -I../..

include $(GNUSTEP_MAKEFILES)/bundle.make

