include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Battery
BUNDLE_EXTENSION = .gsmenuextra

Battery_PRINCIPAL_CLASS = BatteryExtra
Battery_OBJC_FILES = BatteryExtra.m
Battery_RESOURCE_FILES = Info.plist

ADDITIONAL_OBJCFLAGS += -I../..

include $(GNUSTEP_MAKEFILES)/bundle.make
