GNUSTEP_INSTALLATION_DOMAIN = SYSTEM
.PHONY: all server install clean

# Top-level helper Makefile for building the Server.

all: server

server:
	$(MAKE) -C Server

install:
	$(MAKE) -C Server install

clean:
	$(MAKE) -C Server clean

