include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

BUNDLE_NAME = Clock
BUNDLE_EXTENSION = .gsmenuextra

Clock_PRINCIPAL_CLASS = ClockExtra
Clock_OBJC_FILES = ClockExtra.m
Clock_RESOURCE_FILES = Info.plist

ADDITIONAL_OBJCFLAGS += -I../..

include $(GNUSTEP_MAKEFILES)/bundle.make

