include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

BUNDLE_NAME = Brightness
BUNDLE_EXTENSION = .gsmenuextra
Brightness_INSTALL_DIR = /System/Library/MenuExtras

Brightness_PRINCIPAL_CLASS = BrightnessExtra
Brightness_OBJC_FILES = BrightnessExtra.m

ADDITIONAL_OBJCFLAGS += -I../..

include $(GNUSTEP_MAKEFILES)/bundle.make

