include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Brightness
BUNDLE_EXTENSION = .gsmenuextra

Brightness_PRINCIPAL_CLASS = BrightnessExtra
Brightness_OBJC_FILES = BrightnessExtra.m
Brightness_RESOURCE_FILES = Info.plist

ADDITIONAL_OBJCFLAGS += -I../..

include $(GNUSTEP_MAKEFILES)/bundle.make
