include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Sound
BUNDLE_EXTENSION = .gsmenuextra

Sound_PRINCIPAL_CLASS = SoundExtra
Sound_OBJC_FILES = SoundExtra.m ../../SoundVolume.m
Sound_RESOURCE_FILES = Info.plist

ADDITIONAL_OBJCFLAGS += -I../..

include $(GNUSTEP_MAKEFILES)/bundle.make
