include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

TOOL_NAME = wlanauth
wlanauth_OBJC_FILES = wlanauth.m
wlanauth_TOOL_LIBS += -lgnustep-gui -lgnustep-base -lobjc

include $(GNUSTEP_MAKEFILES)/tool.make

