/*
 * Copyright (c) 2026 Simon Peter
 *
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * GWHeaderDatabase - SQLite-backed lookup of which distro package provides
 * a given C/C++ header.
 *
 * The database is generated by Build/tools/build-headerdb.py from the Debian,
 * Arch Linux and FreeBSD repositories and contains only headers that exist in
 * all three.  It is bundled into the PackageManager framework Resources; a
 * future version will download it on demand and keep it versioned.
 */

#import <Foundation/Foundation.h>

@class GWPackageManager;

NS_ASSUME_NONNULL_BEGIN

@interface GWHeaderDatabase : NSObject

+ (instancetype)sharedDatabase;

// Designated initializer; useful for tests and for pointing at a
// user-provided database.  Opens the database immediately; returns nil on
// failure (the error explains why, e.g. the file is missing or corrupt).
- (nullable instancetype)initWithPath:(NSString *)dbPath error:(NSError **)error;

@property (readonly) BOOL isOpen;

// Maps the current OS onto the repository distro used by the database:
// "debian", "arch" or "freebsd".  Returns nil when there is no data for the
// current OS (e.g. OpenBSD), in which case header resolution is a no-op.
- (nullable NSString *)databaseDistroForCurrentOS;

// All package names that install the given header on the given distro
// ("debian", "arch", "freebsd"), in deterministic (alphabetical) order.
- (NSArray<NSString *> *)packagesProvidingHeader:(NSString *)includeName
                                          distro:(NSString *)distro
                                           error:(NSError **)error;

// The single best-matching package for a header, or nil when the header is
// not in the database (or not present on the distro).  "Best" means the
// package whose name matches the header's top-level directory most closely;
// ties are broken by shortest package name, then alphabetically.
- (nullable NSString *)packageForHeader:(NSString *)includeName
                                 distro:(NSString *)distro
                                  error:(NSError **)error;

// Whether the header's installed path (include_prefix || include_name)
// exists on disk.  This is what decides whether a package actually needs
// installing.
- (BOOL)isHeaderInstalled:(NSString *)includeName
                   distro:(NSString *)distro;

// Location of the database file in use (mainly for diagnostics).
@property (readonly, copy) NSString *databasePath;

@end

NS_ASSUME_NONNULL_END