include $(GNUSTEP_MAKEFILES)/common.make

TEST_TOOL_NAME = t_Locator

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework
ADDITIONAL_CPPFLAGS += -I../..

t_Locator_OBJC_FILES = t_Locator.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make
