include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = BootEnvironments
BootEnvironments_OBJC_FILES = main.m AppDelegate.m BootConfigController.m MainView.m
BootEnvironments_PRINCIPAL_CLASS = NSApplication

include $(GNUSTEP_MAKEFILES)/application.make