/*
 * Copyright (c) 2026 Simon Peter
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#import "ProfileGenerator.h"

#include <lcms2.h>

@implementation ProfileGenerator

+ (NSString *)profilesDirectoryForAllUsers:(BOOL)allUsers
{
    if (allUsers) {
        return @"/Library/Color/Profiles";
    }
    NSString *home = NSHomeDirectory();
    return [home stringByAppendingPathComponent:@"GNUstep/Color/Profiles"];
}

+ (BOOL)generateProfileAtPath:(NSString *)path
                         name:(NSString *)name
                   whitePoint:(double)whitePointK
                        gamma:(double)gamma
                   forAllUsers:(BOOL)forAllUsers
{
    cmsHPROFILE hProfile = cmsCreateProfilePlaceholder(NULL);
    if (!hProfile) return NO;

    cmsSetProfileVersion(hProfile, 4.3);
    cmsSetDeviceClass(hProfile, cmsSigDisplayClass);
    cmsSetColorSpace(hProfile, cmsSigRgbData);
    cmsSetPCS(hProfile, cmsSigXYZData);

    cmsToneCurve *gammaCurve = cmsBuildGamma(NULL, gamma);
    if (!gammaCurve) {
        cmsCloseProfile(hProfile);
        return NO;
    }

    cmsToneCurve *rgbTRC[3] = {gammaCurve, gammaCurve, gammaCurve};
    cmsWriteTag(hProfile, cmsSigRedTRCTag, rgbTRC[0]);
    cmsWriteTag(hProfile, cmsSigGreenTRCTag, rgbTRC[1]);
    cmsWriteTag(hProfile, cmsSigBlueTRCTag, rgbTRC[2]);

    cmsCIExyY whiteXY;
    cmsWhitePointFromTemp(&whiteXY, (cmsFloat64Number)whitePointK);
    cmsWriteTag(hProfile, cmsSigMediaWhitePointTag, &whiteXY);

    cmsCIEXYZ black = {0, 0, 0};
    cmsWriteTag(hProfile, cmsSigMediaBlackPointTag, &black);

    cmsFloat64Number matrix[9] = {
        0.436, 0.385, 0.143,
        0.222, 0.717, 0.061,
        0.014, 0.097, 0.714
    };
    cmsWriteTag(hProfile, cmsSigRedColorantTag, &matrix[0]);
    cmsWriteTag(hProfile, cmsSigGreenColorantTag, &matrix[3]);
    cmsWriteTag(hProfile, cmsSigBlueColorantTag, &matrix[6]);

    if (name) {
        cmsMLU *mlu = cmsMLUalloc(NULL, 1);
        if (mlu) {
            cmsMLUsetASCII(mlu, "en", "US", [name UTF8String]);
            cmsWriteTag(hProfile, cmsSigProfileDescriptionTag, mlu);
            cmsMLUfree(mlu);
        }
    }

    cmsMLU *copyright = cmsMLUalloc(NULL, 1);
    if (copyright) {
        cmsMLUsetASCII(copyright, "en", "US", "Generated by ColorAssistant");
        cmsWriteTag(hProfile, cmsSigCopyrightTag, copyright);
        cmsMLUfree(copyright);
    }

    NSString *dir = [path stringByDeletingLastPathComponent];
    NSFileManager *fm = [NSFileManager defaultManager];
    if (![fm fileExistsAtPath:dir]) {
        [fm createDirectoryAtPath:dir withIntermediateDirectories:YES
                       attributes:nil error:NULL];
    }

    BOOL success = (cmsSaveProfileToFile(hProfile, [path UTF8String]) != 0);

    cmsFreeToneCurve(gammaCurve);
    cmsCloseProfile(hProfile);

    return success;
}

@end
