#!/bin/sh

# PROVIDE: loginwindow
# REQUIRE: LOGIN cleanvar moused syscons dbus
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable the LoginWindow:
#
# loginwindow_enable="YES"
#

. /etc/rc.subr

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

name="loginwindow"
rcvar=loginwindow_enable

load_rc_config ${name}

: ${loginwindow_enable:="NO"}

command="/usr/sbin/daemon"
procname="/System/Applications/LoginWindow.app/LoginWindow"
pidfile="/var/run/${name}.pid"
logfile="/var/log/LoginWindow.log"
command_args="-f -o ${logfile} ${procname} --pid-file=${pidfile}"

run_rc_command "$1"